### PR TITLE
QA fixes

### LINKED ISSUE #14: ❓ Query: Multiple Jobber Forms Not Displaying on Frontend – Is this Intentional Behavior?
### Describe your question

When two Jobber forms (e.g., **Request + Booking** or **Request + Request**) are added to a single page, both render correctly in the editor but do **not** display on the frontend.

**Use Case:**

* Admin adds multiple Jobber widgets to a page (e.g., one for a **Request** form and another for a **Booking** form).
* In the Wix Editor, both forms appear as expected.
* On the frontend page, only the first form appears.
* If delete the first form, the second appears.

**Question:**
Is this a known or intentional limitation? Or should multiple Jobber forms be supported on the same page?

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by nicholasio**
### Description of the Change

Closes #14 #12 #10 

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability
> Developer - Non-functional update

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added [Critical Flows, Test Cases, and/or End-to-End Tests](https://10up.github.io/Open-Source-Best-Practices/testing/) to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

File: src/site/widgets/custom-elements/jobber-widget/no-markup.tsx [hunk 1]
```diff
@@ -22,8 +22,7 @@ const NoMarkup: React.FC = () => (
 				textAlign: 'center',
 			}}
 		>
-			To embed a jobber form, open settings (double click the widget) and select which form
-			you want to embed.
+			To embed a jobber form, open settings and select which form you want to embed.
```
Comment (dkotter) [inline src/site/widgets/custom-elements/jobber-widget/no-markup.tsx]:
```suggestion
			To embed a Jobber form, open settings and select which form you want to embed.
```

**Review by dkotter — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
@nicholasio 

I am still facing same issues on the App installed via the link shared https://fueled.slack.com/archives/C08A1SAJ4JY/p1748275454284499. Please confirm if this is the updated app. 


For #10

Still reproducible. 


https://github.com/user-attachments/assets/2690c066-7c3b-4135-9e92-d13dd7aa4d78




----
For #14 

Screenshot 2025-05-30 at 2 39 18 PM
